export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';
export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_BOOKS_LIST = 'FETCH_BOOKS_LIST';
export const SET_VIEW_BOOK_ID = 'SET_VIEW_BOOK_ID';
export const FETCH_LATEST_BOOKS = 'FETCH_LATEST_BOOKS';
