require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'bookz_new' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-static-server', :path => '../node_modules/react-native-static-server'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'RNZipArchive', :path => '../node_modules/react-native-zip-archive'

  pod 'react-native-orientation', :path => '../node_modules/@lightbase/react-native-orientation'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  target 'bookz_newTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'bookz_new-tvOS' do
  # Pods for bookz_new-tvOS

  target 'bookz_new-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
